language: node_js

node_js:
    - "5"

services:
    - mongodb

branches:
  only:
    - develop

install:
    - npm install

before_script:
    - sleep 15
    - mongo mydb_test --eval 'db.addUser("travis", "test");'

script:
    - npm test