language: node_js

node_js:
    - "5"

services:
    - mongodb

branches:
  only:
    - develop

install:
    - npm install

before_script:
    - npm run startdb
    - sleep 15

script:
    - npm test