# running version 2 file will automatically build a network
# between all of the containers defined in this file,
# so we don't need links anymore.

version: "2.0"
services:
    web:
        image: nonoroazoro/zhihu-daily-reader:latest
        depends_on:
            - db
        ports:
            - "8888:8888"
        environment:
            - NODE_ENV=production
        restart: unless-stopped
    db:
        image: mongo:latest
        volumes:
            - ./db:/data/db
        restart: unless-stopped
