# running version 2 file will automatically build a network
# between all of the containers defined in this file,
# so we don't need links anymore.

version: "2"
services:
    web:
        build: .
        image: nonoroazoro/zhihu-daily-reader:1.2.0
        dockerfile: Dockerfile.rpi
        depends_on:
            - db
        ports:
            - "8888:8888"
        environment:
            - NODE_ENV=production
        restart: unless-stopped
    db:
        image: nonoroazoro/rpi-mongo
        volumes:
            - ./db:/data/db
        restart: unless-stopped
